- name: A単adir host al inventario
  hosts: localhost
  gather_facts: false
  vars:
    mac_address: "{{ lookup('env', 'mac_address') }}"
    ip_address: "{{ lookup('env', 'ip_address') }}"
    node_role: "{{ lookup('env', 'node_role') }}"
    inventory_file: "inventario"
  tasks:
    - name: A単adir host al inventario
      add_host:
        name: "{{ ip_address }}"
        ansible_host: "{{ ip_address }}"
        mac_address: "{{ mac_address }}"
        node_role: "{{ node_role }}"
      delegate_to: localhost

    - name: Validar si existe el grupo en el archivo de inventario
      shell: grep -q "\[{{ node_role }}\]" {{ inventory_file }}
      ignore_errors: true
      changed_when: false
      failed_when: false
      register: group_exist

    - name: Establecer group_exist en caso de que grep falle
      set_fact:
        group_exist: "{{ {'rc': 1} if group_exist is failed else group_exist }}"


    - name: A単adir entrada de host al archivo de inventario si no existe el grupo
      lineinfile:
        path: "{{ inventory_file }}"
        line: "\n[{{node_role}}]\n{{ ip_address }} ansible_mac_address={{ mac_address }}"
        insertafter: EOF
      when: group_exist.rc != 0
      delegate_to: localhost

    - name: A単adir entrada de host al archivo de inventario si existe el grupo
      lineinfile:
        path: "{{ inventory_file }}"
        line: "{{ ip_address }} ansible_mac_address={{ mac_address }}"
        insertafter: "\\[{{ node_role }}\\]"
        state: present
      when: group_exist.rc == 0
      delegate_to: localhost
