---
- name: Asignar rol por defecto a todos los hosts                          
  hosts: all
  tasks:
    - name: Aplicar rol por defecto
      include_role:
        name: default
      when: "'00:0c:29:94:b7:28' not in hostvars[inventory_hostname]['ansible_mac_address']"

- name: Aplicar rol alternativo a subgrupo
  hosts: subred2
  roles:
    - alternativo
